Port: 9002
FileType:
  - .pdf
  - .jpg
  - .png
  - .jar
  - .doc
  - .docx
  - .csv
  - .et
  - .ett
  - .xls
  - .xlt
  - .xlsx
  - .xlsm
  - .dbf
  - .xml
  - .html
  - .htm
  - .mhtml
  - .mht
  - .txt
  - .txt
  - .CSV
  - .prn
  - .dif
  - .xltx
  - .xltm
  - .xls
  - .et
  - .ett
  - .xls
  - .xlt
  - .xlsx
  - .xlsm
  - .dbf
  - .xml
  - .html
  - .htm
  - .mhtml
  - .mht
  - .txt
  - .txt
  - .CSV
  - .prn
  - .dif
  - .xltx
  - .xltm
  - .xls
  - .dps
  - .dpt
  - .ppt
  - .pot
  - .pps
  - .pptx
  - .pptm
  - .potx
  - .potm
  - .ppsx
  - .ppsm
  - .jpg
  - .png
  - .tif
  - .bmp
  - .pptx